import { Project } from "./types.ts";

const projects: Project[] = [
  {
    title: "R-TYPE",
    description: "projects.rtype",
    isTeamProject: true,
    groupSize: 4,
    keywords: ["Game Engine", "C++", "Network"],
  },
  {
    title: "AREA",
    description: "projects.area",
    isTeamProject: true,
    groupSize: 4,
    keywords: [
      "Docker",
      "Python",
      "Network",
      "Flask",
      "MySQL",
      "React TS",
      "sass",
      "Flutter",
      "API",
      "OAuth2",
    ],
  },
  {
    title: "TodoList",
    description: "projects.todolist",
    isTeamProject: false,
    keywords: [
      "Docker",
      "Golang",
      "MySQL",
      "Deployment",
      "React TS",
      "sass",
      "clean architecture",
      "Netlify",
      "Render",
    ],
    github: "https://github.com/orgs/Pad-TodoList/repositories",
  },
  {
    title: "Handwritten digits",
    description: "projects.handwrittenDigits",
    isTeamProject: false,
    keywords: ["Python", "Flask", "API", "Tensorflow", "Machine learning"],
    github: "https://github.com/TheRealPad/checkHandWrittenDigits",
  },
  {
    title: "Pokemon companion",
    description: "projects.pokemonCompanion",
    isTeamProject: false,
    keywords: ["Android", "Wear OS", "Kotlin", "Bluetooth", "Native"],
    github: "https://github.com/TheRealPad/pokemon-compagnon",
  },
  {
    title: "Introduction to database system",
    description: "projects.database",
    isTeamProject: false,
    keywords: [
      "MySQL",
      "Python",
      "Discord",
      "Bot",
      "ERD",
      "EER",
      "documentation",
    ],
    github: "soon",
  },
  {
    title: "Software Engineering",
    description: "projects.softwareEngineering",
    isTeamProject: true,
    groupSize: 3,
    keywords: [
      "MySQL",
      "Python",
      "Flask",
      "React JS",
      "Docker",
      "Google Cloud Platform",
      "documentation",
      "API",
    ],
    github: "soon",
  },
];

export { projects };
